apiVersion: apps/v1 
kind: Deployment
metadata:
  name: udpclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udpclient
  template:
    metadata:
      labels:
        app: udpclient
    spec:
      containers:
      - name: client
        image: emretopal20/cmpe492-client
        command: ["python", "client.py"]
        args: ["$(SERVER_IP)"]
        ports:
        - containerPort: 37020
          protocol: UDP
        env:
        - name: SERVER_IP
          value: "172.17.0.3"

