apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  storageClassName: mystorage
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
  claimRef:
    name: mypvc
    namespace: default
