apiVersion: apps/v1 
kind: Deployment
metadata:
  name: udpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udpserver
  template:
    metadata:
      labels:
        app: udpserver
    spec:
      volumes:
        - name: mymount
          persistentVolumeClaim:
            claimName: mypvc
      containers:
      - name: server
        image: emretopal20/cmpe492-server
        ports:
        - containerPort: 3000
        env:
        - name: LOGFILE_PATH
          value: "/storage/server.log"
        command: ["python", "server.py"]
        args: ["/storage/server.log"]
        volumeMounts:
          - mountPath: "/storage"
            name: mymount